# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KC_eNTv9NFtHCjXR2hSfGE_s-lXtBqZf
"""

height = float(input("請輸入你的身高(公尺):"))
weight = float(input("請輸入你的體重(公斤):"))
BMI = weight/(height**2)
print(f"您的BMI是:{BMI:.2f}")